#!/usr/bin/env bash
#username, user id, home directory path

while IFS=: read -r username password uid gid gecos home shell; do
    echo "$username:$uid:$home"
done < /etc/passwd
~                     
