#!/usr/bin/env bash
#username, user id, home directory path

while IFS=: read -r username password uid gid gecos home shell; do
    echo "Username: $username, UID: $uid, Home: $home"
done < /etc/passwd
