#!/usr/bin/env bash
#a little story of passwd

while IFS=: read -r username password uid gid gecos home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $username's place is protected by the passcode $password, more info about the user here: $uid $gecos"
done < /etc/passwd
