#!/usr/bin/env bash
#this script displays unlucky numbers in some countries


num=1
while [ $num -le 20 ]
do
	case $num in
        4)
            echo "$num"
            echo "bad luck from China"
            ;;
        9)
            echo "$num"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$num"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$num"
            ;;
    esac
    ((num++))
	
done
