#!/usr/bin/env bash
#a lot of work
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f  "/var/run/myscript.pid"; exit 0' SIGQUIT SIGTERM
while true; do
	echo "To infinity and beyound"
	sleep 1
done
