#!/usr/bin/env bash
#a lot of processes

echo $$ > /var/run/myscript.pid


term_handler() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}


int_handler() {
    echo "Y U no love me?!"
}


quit_handler() {
    echo "Cleaning up and quitting..."
    rm -f /var/run/myscript.pid
    exit 0
}


trap term_handler SIGTERM
trap int_handler SIGINT
trap quit_handler SIGQUIT


while true; do
    echo "To infinity and beyond"
    sleep 2
done
