#!/usr/bin/env bash
# a lot of work

SCRIPT_PATH="/home/student_jail/10-process_and_pid_file"
PID_FILE="/var/run/myscript.pid"
su - student_jail -c "$SCRIPT_PATH" &
echo $! > "$PID_FILE"
handle_sigterm() {
    echo "I hate the kill command"
    cleanup_and_exit
}

handle_sigint() {
    echo "Y U no love me?!"
}
handle_sigquit() {
    cleanup_and_exit
}

cleanup_and_exit() {
    sudo rm -f "$PID_FILE"
    exit 0
}
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT


while true; do
    echo "To infinity and beyond"
    sleep 1
done
